class Error(Exception):
    pass


class ResourceExhaustedError(Exception):
    pass
